Javascript: level1
digitalisx/web-practice pull request #18
Opened 2022-07-12 13:53 UTC by subin5

- 첫번째 문제 : https://school.programmers.co.kr/learn/courses/30/lessons/12903
- 두번째 문제 : https://school.programmers.co.kr/learn/courses/30/lessons/12948

2022-07-12 14:01 UTC, digitalisx requested changes
늦은 시간 고생하셨습니다!
우선 앞으로 코딩할 때 필요한 스타일과 문법들에 대해 커멘트 드렸습니다. 🙌

2022-07-12 14:01 UTC, digitalisx commented on js-practice/filter_phoneNumber.js
> +    for(var i = 0; i < phone_number.length - 4; i++){
`i` 보다는 `index`와 같이 알아보기 쉬운 변수 명 사용하기

2022-07-12 15:24 UTC, Coreight98 submitted a review, later dismissed
고생많으셨습니다. js는 워낙 변칙적인 요소가 많으셔서, 공부하시기 어려우실 거 같은데, 같이 잘 공부해봐요!

2022-07-12 15:24 UTC, Coreight98 commented on js-practice/middle_char.js
> +    if(str_length % 2 === 0){
삼항연산자를 사용해보셔도 좋을거 같습니다.

2022-07-13 04:25 UTC, subin5 commented on js-practice/filter_phoneNumber.js
> +}
앞으로 고려하겠습니다

2022-07-13 05:19 UTC, subin5 commented on js-practice/filter_phoneNumber.js
> +function solution(phone_number) {
Typescript 확장 파일에서만 유효합니다.

2022-07-13 05:52 UTC, digitalisx approved these changes
@subin5 좋아보입니다! 고생 많으셨어요~

2022-07-13 05:54 UTC, merged