Vue: tutorial practice
digitalisx/web-practice pull request #39
Opened 2022-08-03 11:07 UTC by subin5

Resolves: #38

학습 내용
-
- `Node.js`를 이용한 `vue` 프로젝트 생성
- 데이터 바인딩
- 반복문
- 이벤트 핸들러
- 함수
- 모달창
- 조건문
- import / export

2022-08-03 11:14 UTC, digitalisx commented
@Coreight98 Vue에도 관심이 있으시면, 시간 나실 때 간단한 리뷰 부탁드립니다. :)

2022-08-05 06:45 UTC, digitalisx requested changes
@subin5 2주간 고생하셨습니다, 많이 발전한 것 같아서 좋습니다.
몇가지 커멘트를 남겼으니 참고 부탁드려요! 🙌

2022-08-05 06:45 UTC, digitalisx commented on .gitignore
> +node_modules
EOF 추가 바랍니다.

2022-08-05 06:45 UTC, digitalisx commented on src/vue/vuedongsan/package.json
> +  },
`dependencies`와 `devDependencies`의 차이가 뭔가요?

2022-08-05 06:45 UTC, digitalisx commented on src/vue/vuedongsan/package.json
> +{
`package.json`와 `package-lock.json` 역할의 차이는 무엇인가요?

2022-08-05 06:45 UTC, digitalisx commented on src/vue/vuedongsan/src/App.vue
> +  margin: 0
Style 부분은 별도의 CSS 파일로 분리 해볼까요?

2022-08-05 06:45 UTC, digitalisx commented on src/vue/vuedongsan/src/components/HelloWorld.vue
> +<style scoped>
여기 Style도 마찬가지!

2022-08-05 06:45 UTC, digitalisx commented on src/vue/vuedongsan/vue.config.js
> +module.exports = defineConfig({
한줄만 띄워주세요~
```suggestion
const { defineConfig } = require('@vue/cli-service')

module.exports = defineConfig({
```

2022-08-05 06:45 UTC, digitalisx commented on src/vue/vuedongsan/src/assets/oneroom.js
> +    price: 340000
괄호 안에 있는 JSON 요소들은 탭으로 Indent를 넣어주세요

```suggestion
      id : 0,
      title: "Sinrim station 30 meters away",
      image: "https://codingapple1.github.io/vue/room0.jpg",
      content: "18년 신축공사한 남향 원룸 ☀️, 공기청정기 제공",
      price: 340000
```

2022-08-05 06:51 UTC, subin5 commented on .gitignore
> +node_modules
gitignore에도 EOF를 추가하는군요! 감사합니다.

2022-08-08 07:33 UTC, subin5 commented on src/vue/vuedongsan/src/assets/oneroom.js
> +    price: 340000
EOF까지 추가 했습니다 :D

2022-08-08 07:41 UTC, subin5 commented on src/vue/vuedongsan/package.json
> +  },
`dependencies`는 프로덕션 환경에서 응용 프로그램에 필요한 패키지로, 애플리케이션의 동작과 직접적인 연관이 있기 때문에 **배포용 라이브러리**라고 생각하시면 됩니다.

`devDependencies`는 로컬 개발 및 테스트에만 필요한 패키지로, **배포할 때 포함되지 않는 라이브러리**입니다. 그래서 어플의 로직과 관련없다고 판단되는 라이브러리는 `devDependencies`에 넣는 것이 좋습니다!

추가로 설치법도 다르기 때문에 참고하시면 좋을 것 같습니다
- `dependencies` : **npm install 라이브러리명**
- `devDependencies` : **npm install 라이브러리명 --save-dev** 혹은 **npm install 라이브러리명  -D**

2022-08-08 08:50 UTC, subin5 commented on src/vue/vuedongsan/package.json
> +{
`package.json`에는 기본적으로 프로젝트에 대한 정보가 저장됩니다.
특히 패키지 버전이 `version range` 형태로 저장이 되는데, 
이 때 발생하는 버전의 불명확함을 보충하고자 `package-lock.json`을 사용합니다.

따라서 `package.json`에는 버전 정보가 `version range` 형태로 저장이 되고,
`package.json`에는 정확한 버전 정보가 저장됩니다.

2022-08-08 09:05 UTC, subin5 commented on src/vue/vuedongsan/package.json
> +{
추가로 `version range` 표기 방식으로 `~(틸드)` 혹은 `^(캐럿)`을 많이 씁니다.
관련 내용은 https://blog.outsider.ne.kr/1041 참고

2022-08-08 09:13 UTC, subin5 commented on src/vue/vuedongsan/src/components/HelloWorld.vue
> +<style scoped>
`HelloWorld.vue`는 필요 없는 파일이라 삭제했습니다

2022-08-16 10:08 UTC, digitalisx commented on src/vue/vuedongsan/package.json
> +{
다음에는 `yarn`을 써보면 좋을거같습니다, 내용은 맞습니다 고생 많았어요!

2022-08-16 10:09 UTC, digitalisx approved these changes
LGTM

2022-08-16 10:20 UTC, merged

2022-08-16 10:21 UTC, digitalisx commented
@subin5 병합한 브랜치는 삭제 부탁드려요 :)

2022-08-17 11:48 UTC, Coreight98 commented on src/vue/vuedongsan/package.json
> +{
yarn보시면서 이것도 보시면 좋을거 같아요! [링크](https://toss.tech/article/node-modules-and-yarn-berry)